Vagrant.configure("2") do |config|
  # Red Hat VM
  config.vm.define "redhat_vm" do |rh|
    rh.vm.box = "almalinux/9"
    rh.vm.hostname = "redhat"
    rh.vm.network "private_network", ip: "192.168.11.11"

    rh.vm.provision "shell", inline: <<-SHELL
echo 'insecure' >> /etc/curlrc
git config --system http.sslVerify false
dnf update -y
dnf install -y zip unzip wget httpd 
systemctl start httpd
systemctl enable httpd
SHELL
  end

  # Debian VM
  config.vm.define "debian_vm" do |db|
    db.vm.box = "debian/bullseye64"
    db.vm.hostname = "debian"
    db.vm.network "private_network", ip: "192.168.12.12"

    db.vm.provision "shell", inline: <<-SHELL
echo 'insecure' >> /etc/curlrc
git config --system http.sslVerify false
apt-get update -y
apt-get install -y zip unzip wget apache2
systemctl start apache2
systemctl enable apache2
SHELL
  end
end
